const GEN_MIN = 0;
const GEN_MAX = 127;

const DEFAULT_RANGE = [GEN_MIN, GEN_MAX];
const DEFAULT_STEP_INCREMENT = 0.5;
const DEFAULT_STEP_INCREMENT_SINE = 0.05;
const DEFAULT_FPS = 60;
const DEFAULT_BEATS_PER_FRAME = 4;

const DEFAULT_BPM = DEFAULT_FPS * DEFAULT_BEATS_PER_FRAME;
const DEFAULT_FRAMES_PER_BEAT = DEFAULT_BPM / DEFAULT_FPS;

const LOOPATRON_DEBUG = true;

export {
    GEN_MIN,
    GEN_MAX,
    DEFAULT_RANGE,
    DEFAULT_STEP_INCREMENT,
    DEFAULT_STEP_INCREMENT_SINE,
    DEFAULT_FPS,
    DEFAULT_BEATS_PER_FRAME,
    DEFAULT_BPM,
    DEFAULT_FRAMES_PER_BEAT,
    LOOPATRON_DEBUG
};
